# 第 17 讲：多模态模型

这是 CS336 Lecture 17 的可执行中文学习版。

- 官方来源：`external/cs336-lectures/lecture_17.py`
- 官方形式：executable lecture
- 英文标题：Multimodal Models

这份 notebook 是学习版，不是逐字翻译。它按官方讲义的结构和节奏整理主线，并在适合的位置加入小实验。


## 0. 本讲你要抓住什么

这一讲讲语言模型如何接入图像、音频、视频等模态：把不同模态转成 token-like 表示，再通过 projector、encoder 或统一架构和语言模型连接。

学习方式：

1. 先读每节的中文解释。
2. 运行对应代码 cell。
3. 改一个参数，观察输出如何变化。
4. 最后用检查点问题自测。


## 1. 本讲路线图

多模态输入、视觉 encoder、patch token、CLIP/VLM、统一 token 序列和训练阶段。


In [1]:
lecture = 17
title = 'Multimodal Models'
source = 'external/cs336-lectures/lecture_17.py'
print(f"Lecture {lecture}: {title}")
print("source:", source)


Lecture 17: Multimodal Models
source: external/cs336-lectures/lecture_17.py


## 2. 核心问题

语言模型吃 token 序列，图像/音频/视频必须先变成可对齐的向量序列。


## 3. Vision Transformer

把图像切成 patch，每个 patch 类似一个视觉 token，再加位置编码进入 Transformer。


## 4. CLIP 直觉

用图文对比学习把图像和文本映射到同一个语义空间。


## 5. VLM 连接方式

常见方法是视觉 encoder + projector + LLM，或者更统一的 multimodal token 模型。


## 6. Token budget

图像和视频会消耗大量 token/patch，压缩和对齐很重要。


## 动手实验 1：图像 patchify 玩具版

先直接运行，再改一个数字或字符串。


In [2]:
import numpy as np

image = np.arange(4 * 4).reshape(4, 4)
patch_size = 2
patches = []
for i in range(0, image.shape[0], patch_size):
    for j in range(0, image.shape[1], patch_size):
        patches.append(image[i:i+patch_size, j:j+patch_size].reshape(-1))
print(image)
print("patches:")
for p in patches:
    print(p)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
patches:
[0 1 4 5]
[2 3 6 7]
[ 8  9 12 13]
[10 11 14 15]


## 动手实验 2：视频 token budget 粗算

先直接运行，再改一个数字或字符串。


In [3]:
frames = 32
patches_per_frame = 14 * 14
visual_tokens = frames * patches_per_frame
text_tokens = 512
print("visual tokens:", visual_tokens)
print("total tokens:", visual_tokens + text_tokens)


visual tokens: 6272
total tokens: 6784


## 今日检查点

1. 能解释为什么图像要 patchify。
2. 能说出视觉 encoder + projector + LLM 的基本结构。
3. 能理解多模态模型为什么容易受 token budget 限制。

如果这些能讲清楚，这一讲的第一轮学习就完成了。
